name: micro_app_login
description: A new Flutter package project.
version: 1.0.4
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  micro_core:
    path: ../../../packages/micro_core

  micro_commons_design_system:
    path: ../../../packages/micro_commons/micro_commons_design_system

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
